Scripts: More consistent error messages.

diff --git a/scripts/.local/bin/cat-videos b/scripts/.local/bin/cat-videos
--- a/scripts/.local/bin/cat-videos
+++ b/scripts/.local/bin/cat-videos
@@ -10,7 +10,7 @@ fi
 
 for arg in "$@"; do
     if [ ! -f "$arg" ]; then
-        echo "'$arg' is not a file." >&2
+        echo "File not found: '$arg'" >&2
         exit 1
     fi
     printf "file '%s'\n" "$(realpath "$arg")" >> "$tmpfile"
diff --git a/scripts/.local/bin/md5rename b/scripts/.local/bin/md5rename
--- a/scripts/.local/bin/md5rename
+++ b/scripts/.local/bin/md5rename
@@ -2,9 +2,8 @@
 set -euo pipefail
 
 inf=${1:-}
-if [ -z "$inf" ] || [ ! -e "$inf" ]
-then
-    echo "File \"$inf\" not found."
+if [ -z "$inf" ] || [ ! -e "$inf" ]; then
+    echo "File not found: '$inf'" >&2
     exit 1
 fi
 
diff --git a/scripts/.local/bin/ogg-crunch b/scripts/.local/bin/ogg-crunch
--- a/scripts/.local/bin/ogg-crunch
+++ b/scripts/.local/bin/ogg-crunch
@@ -5,7 +5,7 @@ set -euo pipefail
 inf=${1:-}
 if [[ -z "$inf" || ! -e "$inf" ]]
 then
-    echo "File not found."
+    echo "File not found: '$inf'" >&2
     exit 1
 fi
 inf=$(realpath "$inf")
diff --git a/scripts/.local/bin/squarecut b/scripts/.local/bin/squarecut
--- a/scripts/.local/bin/squarecut
+++ b/scripts/.local/bin/squarecut
@@ -3,7 +3,7 @@ set -euo pipefail
 
 inf=${1:-}
 if [ -z "$inf" ] || [ ! -e "$inf" ]; then
-    echo "File '$inf' not found." >&2
+    echo "File not found: '$inf'" >&2
     exit 1
 fi
 out="${2:-$inf}"
diff --git a/scripts/.local/bin/vgm2mp3 b/scripts/.local/bin/vgm2mp3
--- a/scripts/.local/bin/vgm2mp3
+++ b/scripts/.local/bin/vgm2mp3
@@ -3,7 +3,7 @@ set -euo pipefail
 
 abort() {
     if [ -n "${1:-}" ]; then
-        echo "$1" 1>&2
+        echo "$1" >&2
     fi
     exit 1
 }
@@ -16,14 +16,14 @@ export -f convert
 for arg in "$@"; do
     # Combining these if statements is a headache.
     if [ ! -f "$arg" ]; then
-        abort "File '$arg' does not exist."
+        abort "File not found: '$arg'"
     fi
     if file "$arg" | grep -q 'gzip compressed'; then
         if [ "$(gzip -cd "$arg" | head -c 4)" != "Vgm " ]; then
-            abort "'$arg' is not a VGM file."
+            abort "Not a VGM file: '$arg'"
         fi
     elif [ "$(head -c 4 "$arg")" != "Vgm " ]; then
-        abort "'$arg' is not a VGM file."
+        abort "Not a VGM file: '$arg'"
     fi
 done
 
diff --git a/scripts/.local/bin/wav2ogg b/scripts/.local/bin/wav2ogg
--- a/scripts/.local/bin/wav2ogg
+++ b/scripts/.local/bin/wav2ogg
@@ -3,7 +3,7 @@ set -euo pipefail
 
 dir=${1:-}
 if [ -z "$dir" ] || [ ! -d "$dir" ]; then
-    echo "Directory '$dir' not found." >&2
+    echo "Directory not found: '$dir'" >&2
     exit 1
 fi
 
